config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'blogs#index'

  resources :blogs
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user

  validates :text, presence: true

  def show_text
    if self.text.length > 200
      self.text[0, 200] + "..."
    else
      self.text[0, 200]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blogs

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

    private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @blogs = Blog.all.includes(:user).order('created_at DESC')
    gon.blogs = @blogs
  end

  def show
    @blog = Blog.find(params[:id])
    gon.blog = @blog
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      save_success("投稿しました！")
    else
      render action: :new
    end
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update_attributes(blog_params)
      save_success("投稿を更新しました！")
    else
      render action: :edit
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    if @blog.destroy
      save_success("投稿を削除しました")
    else
      render action: :index
    end
  end

    private
    def blog_params
      params.require(:blog).permit(
        :title,
        :text
        ).merge(user_id: current_user.id)
    end

    def save_success(message)
      flash[:notice] = message
      redirect_to :root
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @blogs = Blog.where(user_id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.haml
.row
  = form_for @blog, html: {class: 'col s12'} do |f|
    .row
      .col.s3
      .input-field.col.s6
        %p.edit-label タイトルを編集する
        = f.text_area :title, class: "materialize-textarea", id: "edit-title"
    .row
      .col.s2
      .input-field.col.s8
        %p.edit-label 記事を編集する
        = f.text_area :text, class: "materialize-textarea", id: "edit-text"
      .col.s12#blog_submit
        =f.submit :投稿する, class: "waves-effect waves-light blue btn"

app/views/blogs/index.html.haml
-@blogs.each do |blog|
  = render 'shared/card', blog: blog

app/views/blogs/new.html.haml
.row
  = form_for @blog, html: {class: 'col s12'} do |f|
    .row
      .col.s3
      .input-field.col.s6
        =f.label :title, "タイトルを入力", for: "textarea1"
        = f.text_area :title, class: "materialize-textarea", id: "textarea1"
    .row
      .col.s2
      .input-field.col.s8
        =f.label :text, "記事を書く", for: "textarea2"
        = f.text_area :text, class: "materialize-textarea", id: "textarea2"
      .col.s12#blog_submit
        =f.submit :投稿する, class: "waves-effect waves-light blue btn"

app/views/blogs/show.html.haml
.row
  .col.s12.m3
  .col.s12.m6
    .card.white
      .card-content.black-text{data: @blog.id}
        %span.card-title= @blog.title
        %p.text-body= @blog.show_text
        %br/
        %p= "Written by : " + @blog.user.nickname
      .card-action
        - if user_signed_in? && @blog.user.id == current_user.id
          = link_to "投稿を編集", edit_blog_path(@blog.id), class: "waves-effect waves-light blue btn"
          = link_to "投稿を削除", "/blogs/#{@blog.id}", method: :delete, class: "waves-effect waves-light blue btn",  data: { turbolinks: false }

app/views/layouts/_navbar.html.haml
%nav.blue
  .nav-wrapper
    %a#service-name.brand-logo.nav-element{"data-turbolinks" => "false", :href => "/"} BLOG
    %ul#nav-mobile.right.hide-on-med-and-down
      - if user_signed_in?
        %li
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-element",  data: { turbolinks: false }
        %li
          = link_to "マイブログ", user_path(current_user.id), class: "nav-element",  data: { turbolinks: false }
        %li
          = link_to "新規投稿", new_blog_path, class: "waves-effect waves-light green btn", id: "post_btn"
      - else
        %li
          = link_to "ログイン", new_user_session_path, class: "nav-element",  data: { turbolinks: false }
        %li
          = link_to "新規登録", new_user_registration_path, class: "nav-element",  data: { turbolinks: false }
      %li
        = link_to "MODE::G", "#", id: "mode-g", class: "nav-element mode-btn",  data: { turbolinks: false }
      %li
        = link_to "MODE::P", "#", id: "mode-p", class: "nav-element mode-btn",  data: { turbolinks: false }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MiniApp
    = Gon::Base.render_data
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:crossorigin => "anonymous", :integrity => "sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=", :src => "https://code.jquery.com/jquery-3.3.1.js"}
    / Compiled and minified CSS
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css", :rel => "stylesheet"}/
    / Compiled and minified JavaScript
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"}
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
  %body
    = render 'layouts/navbar'
    = render 'layouts/notifications'
    = yield

app/views/shared/_card.html.haml
.row
  .col.s12.m3
  .col.s12.m6
    .card.white
      .card-content.black-text{data: blog.id}
        %span.card-title= blog.title
        %p.text-body= blog.show_text
        %br/
        %p= "Written by : " + blog.user.nickname
      .card-action
        = link_to "詳細を見る", blog_path(blog.id), class: "waves-effect waves-light blue btn",  data: { turbolinks: false }
        - if user_signed_in? && blog.user.id == current_user.id
          = link_to "投稿を編集", edit_blog_path(blog.id), class: "waves-effect waves-light blue btn"
          = link_to "投稿を削除", "/blogs/#{blog.id}", method: :delete, class: "waves-effect waves-light blue btn",  data: { turbolinks: false }

app/views/users/show.html.haml
%h3.page-title= current_user.nickname + "さんの記事一覧"
- @blogs.each do |blog|
  = render 'shared/card', blog: blog